### PR TITLE
fix: make `transformer` compatible with `@tiptap/core@^2.0.0-beta.210`

### PR DESCRIPTION
**Pull request by Deckluhm**
Fixes https://github.com/ueberdosis/hocuspocus/issues/510

Ideally it would be great to merge https://github.com/ueberdosis/hocuspocus/pull/511 first.

### CODE REVIEW

**Comment by janthurau** [comment]
@Deckluhm thanks for this! There seem to be quite a few issues right now on TipTap-Side, so if possible I'd just wait a bit more and then directly move to the fixed version (probably once https://github.com/ueberdosis/tiptap/pull/3720 is merged)

**Comment by Deckluhm** [comment]
I wasn't aware of this Tiptap issue since `@tiptap/core@^2.0.0-beta.210` is working fine on my side with this PR.

If the issue is impacting `@tiptap/core`, we can definitely wait for the PR to be merged :+1:

**Comment by Deckluhm** [comment]
It got merged a few hours ago so I just updated my PR with `@tiptap/core@^2.0.0-beta.214` (which is the minimum required version to get the fix).

**Comment by svenadlung** [comment]
@Deckluhm I think 214 should restore the old path 😂 But still I think your way of importing is even better. 
@bdbch what do you think?

**Comment by bdbch** [comment]
I thought about this for a few minutes and I think having those types imported directly from the project would be cleaner and/or easier to use and discover.

Example:

```
import { Extensions } from '@tiptap/core
```

or

```
import { Extensions } from '@tiptap/core/types'
```

but I'd stick with the first one. I think this should already work with a lot of existing typings but it seems some are not exported from the entryfile / entry types file.

**Comment by bdbch** [comment]
Obv. we would need to change this in the @tiptap/core package though.

**Comment by Deckluhm** [comment]
> Obv. we would need to change this in the @tiptap/core package though.

`import { Extensions } from '@tiptap/core` is already possible with current `@tiptap/core`.

**Comment by Deckluhm** [comment]
Is there anything preventing the merge of this PR?

**Review by janthurau — APPROVED** [review]
@Deckluhm Thanks! I've just pushed an update to .217 and will merge soon :)

**Pull request merged**
