### PR TITLE
feature/multiplexing

### PR DESCRIPTION
**Pull request by janthurau**
Not ready at all - WIP! refs #249, #283, #343, #455

Feedback & Contributions are more than welcome :-)

**The idea:**
* Extend the current messaging protocol and add a field at the beginning that indicates the documentName. We can later on even add another field to indicate the yjs subdoc Id.
* In order to keep most of the Hocuspocus server as it is, a websocket connection can now have multiple `Connection` instances that each only reacts to messages affecting them (by checking the documentName). `Connection`s are spawned by another onMessage listener on the WebSocket, so make sure that all messages are handled.
* Provider: not sure yet. Either the provider gets separated from the Websocket (in that case, two open documents would require two providers that each get the same WebSocket injected. Would also open the possibility of just injecting an existing Websocket connection), but that looked rather complicated. An alternative might be just allowing to pass multiple ydocs to the same provider.

**Protocol:**

Before:
`[HocuspocusMessageType][YjsMessageType][yjs binary]`

After:
`[documentName][HocuspocusMessageType][YjsMessageType][yjs binary]`

**Current Status:**
* Both provider and server are adjusted to include the current documentName. Syncing seems to work fine

**Current ToDos:**

- [x] Adjust the provider to allow opening a second document
- [x] The server needs to listen for a CLOSE message. This can be be sent by the provider to close a document without closing the entire connection
- [ ] The server should emit an 'ready' message once the connection is established, so that providers know it's safe to send first sync step
- [x] Check & add tests (e.g. for new CLOSE message)
- [x] Check all hooks - e.g. onStoreDocument, does the debounce work properly with different documents?
- [ ] Check all extensions (e.g. extension-redis - as long as hooks work fine it should be good)
- [x] Update broadcast messages
- [ ] ... ?

**Planned release:**
v2.0.0

** Breaking changes: **
* All yjs messages are now prefixed with the name of the document (including redis messages)
* All methods related to the connection have been moved to the providerwebsocket instance (e.g. disconnect(), connect(), etc)

### CODE REVIEW

**Comment by raineorshine** [comment]
Thanks for opening this WIP!

My use case is a large graph with 1 million+ nodes represented as top-level documents with unique room names for flexible lazy loading.

> * Provider: not sure yet. Either the provider gets separated from the Websocket (in that case, two open documents would require two providers that each get the same WebSocket injected. Would also open the possibility of just injecting an existing Websocket connection), but that looked rather complicated. An alternative might be just allowing to pass multiple ydocs to the same provider.

Most of the YJS providers assume one document per provider: `y-webrtc`, `y-websocket`, and `y-indexeddb` among others. The user is expected to create a separate provider instance for each document, though it should be noted that this is more out of necessity than out of a deeply thought out design. [y-leveldb](https://github.com/yjs/y-leveldb#use-it) appears to be an exception, as all document operations are keyed by `docName`.

In hocuspocus, all of the provider configuration options are related to the Websocket connection. Only `document` (and `awareness`?) are document-specific. 

The provider events are much more split:

Websocket connection events:

- open
- connect
- close
- disconnect
- destroy

Doc-specific events:

- authenticated
- authenticationFailed
- message
- outgoingMessage
- synced
- awarenessUpdate
- awarenessChange

With multiple docs per provider, the config and events API's are largely preserved. You would simply add an additional `docname` argument to each of the doc-related events for subscribers. One document per provider would require larger changes to the API. Websocket connection config and events would need to be handled separately, but still easily shared among provider instances.

The downside of multiple docs per provider is that you then need to internally manage a list of docs, including add/remove, subscribe/unsubscribe, and connect/disconnect.

Personally I went in circles and didn't come to a conclusion, but hopefully sharing my thought process helps your thought process in some way :).

**Comment by raineorshine** [comment]
I've started testing this branch in my app. Thanks again for all your work!

First thing I am noticing is that `HocuspocusProvider.on('status', ...)` is passing `{ event: { status } }` to my handler instead of `{ status }`. Is this expected?

`HocuspocusProviderWebsocket.on('status', ...)` passes `{ status }`.

**Comment by janthurau** [comment]
@raineorshine thanks! That should not happen, seems I mixed something up as I remember explicitely adding this 🤔 Have you progressed further or shall I check/fix that first?

**Comment by raineorshine** [comment]
I'm going to do some more testing. I'm getting an issue where only part of a transaction is completing and I need to isolate it.

**Comment by raineorshine** [comment]
> @raineorshine thanks! That should not happen, seems I mixed something up as I remember explicitely adding this 🤔 Have you progressed further or shall I check/fix that first?

```patch
diff --git a/packages/provider/src/HocuspocusProvider.ts b/packages/provider/src/HocuspocusProvider.ts
index 29b58e40..068a7f67 100644
--- a/packages/provider/src/HocuspocusProvider.ts
+++ b/packages/provider/src/HocuspocusProvider.ts
@@ -149,25 +149,25 @@ export class HocuspocusProvider extends EventEmitter {
     this.on('authenticationFailed', this.configuration.onAuthenticationFailed)
 
     this.configuration.websocketProvider.on('connect', this.configuration.onConnect)
-    this.configuration.websocketProvider.on('connect', (e: Event) => this.emit('connect', { event: e }))
+    this.configuration.websocketProvider.on('connect', (e: Event) => this.emit('connect', e))
 
     this.configuration.websocketProvider.on('open', this.onOpen.bind(this))
-    this.configuration.websocketProvider.on('open', (e: Event) => this.emit('open', { event: e }))
+    this.configuration.websocketProvider.on('open', (e: Event) => this.emit('open', e))
 
     this.configuration.websocketProvider.on('message', this.onMessage.bind(this))
 
     this.configuration.websocketProvider.on('close', this.onClose.bind(this))
     this.configuration.websocketProvider.on('close', this.configuration.onClose)
-    this.configuration.websocketProvider.on('close', (e: Event) => this.emit('close', { event: e }))
+    this.configuration.websocketProvider.on('close', (e: Event) => this.emit('close', e))
 
     this.configuration.websocketProvider.on('status', this.onStatus.bind(this))
-    this.configuration.websocketProvider.on('status', (e: Event) => this.emit('status', { event: e }))
+    this.configuration.websocketProvider.on('status', (e: Event) => this.emit('status', e))
 
     this.configuration.websocketProvider.on('disconnect', this.configuration.onDisconnect)
-    this.configuration.websocketProvider.on('disconnect', (e: Event) => this.emit('disconnect', { event: e }))
+    this.configuration.websocketProvider.on('disconnect', (e: Event) => this.emit('disconnect', e))
 
     this.configuration.websocketProvider.on('destroy', this.configuration.onDestroy)
-    this.configuration.websocketProvider.on('destroy', (e: Event) => this.emit('destroy', { event: e }))
+    this.configuration.websocketProvider.on('destroy', (e: Event) => this.emit('destroy', e))
 
     this.awareness.on('update', () => {
       this.emit('awarenessUpdate', { states: awarenessStatesToArray(this.awareness.getStates()) })
```

**Comment by raineorshine** [comment]
I encountered an issue where it doesn't sync when there is an `onAuthenticate` hook, even if it is empty.

```ts
const server = Server.configure({
  onAuthenticate: async () => {}
})
```

This occurs when there is one `HocuspocusProviderWebsocket` and multiple `HocuspocusProvider` instances. The websocket is authenticated, but updates from one client don't get synced to others. I checked out hocuspocus `v1.1.0` and it works as expected.

**Comment by janthurau** [comment]
hey @ChasLui, @ahoyahoy, @DanSnow, @HelloAlexPan, @martinboksa, @lele0108, @shahriar-shojib,

mentioning all of you because you’ve asked for multiplexing support in the past. If you don’t need this anymore, sorry, you can stop reading :-)

I’ve just released a 2.0.0-alpha.0 pre-release to npm, which includes multiplexing (i.e. using one websocket connection for synchronization of multiple documents). The status is still a bit early, but I already wanted to gather as much feedback as possible and find potential testers in the community. I currently do not have a bigger project where I can test this, so if you can use multiplexing in your project and are willing to give the current implementation a try, this would be much appreciated and helps to get this merged.

On the frontend side, all connection logic has been split to a new ‘HocuspocusProviderWebsocket’, which needs to be passed to your HocuspocusProvider(s). So if you want to synchronize three documents, you’ll create one `HocuspocusProviderWebsocket` and three `HocuspocusProvider`, which gets passed the websocket (`webSocket` param). Authentication works per document, so the URL has to be passed to the HocuspocusProviderWebsocket, tokens to the provider related with the document. A working example can be found in `playground/frontend/src/pages/Index.vue`. Provider events are filtered by documentName, so the frontend shouldnt require further changes. Same on the backend, note that internally we’re spawning different `Connection` instances that each handle one document connection (through the same websocket). If you are somehow parsing the websocket messages yourself, please note that the protocol has changed and now includes the documentName at the first segment of the message.

You can find the PR here for details: https://github.com/ueberdosis/hocuspocus/pull/484

If you need any help, feel free to ping me on Discord or send me a direct message. We can even jump on a quick call if you are willing to help here. 

NPM: https://www.npmjs.com/package/@hocuspocus/server/v/2.0.0-alpha.0
Github Release: https://github.com/ueberdosis/hocuspocus/releases/tag/v2.0.0-alpha.0

**Comment by husseinraoouf** [comment]
First Great work on the feature

I am testing this with an lexical and unfortunately it is not working because the lexical collaboration plugin calls `connect` on the yjs provider and the `HocuspocusProvider` doen't have `connect` now

I think the Provider should have the `connect` method that just call connect of the undelying HocuspocusWebsocketProvider if not connected yet or does noting if already connected

Thank you

**Pull request merged**
